import { LanguageCode, LanguageCodes, LocalizedString, MapLocation } from "../models/Common"
import { EnslaverContributionType, EnslaverContribution } from "../models/EnslaverContribution";
import { IEnslaversService, parseEnslaverContribution } from "../services/EnslaversService"
import { IGeoService } from "../services/GeoService"
import { ILocalizationService } from "../services/LocalizationService";
import { ServiceContext } from "../services/ServiceContext";

const mockEditEnslaverContribData = {
    "type": "edit",
    "identities": {
        "1003149": {
            "id": 1003149,
            "personal_data": {
                "principal_alias": "Boats, William",
                "birth_year": 1716,
                "birth_month": 9,
                "birth_day": 3,
                "birth_place_id": 1720,
                "death_year": 1794,
                "death_month": 10,
                "death_day": 28,
                "death_place_id": 1720,
                "father_name": "James",
                "father_occupation": "Barber",
                "mother_name": null,
                "probate_date": "4-Jul-1795",
                "will_value_pounds": null,
                "will_value_dollars": null,
                "will_court": "PCC",
                "principal_location_id": null,
                "notes": ""
            },
            "aliases": {
                "1008760": {
                    "id": 1008760,
                    "name": "Boats, William",
                    "voyages": [{
                        "voyage__voyage_id": 91142,
                        "voyage__voyage_ship__ship_name": "Nelly",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83975,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1781",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83976,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1784",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83977,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1784",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83978,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1785",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 83979,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1787",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83980,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1788",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 83981,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 83982,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 83983,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 83984,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83985,
                        "voyage__voyage_ship__ship_name": "Vulture",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 91148,
                        "voyage__voyage_ship__ship_name": "Sampson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1764",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 402
                    }, {
                        "voyage__voyage_id": 91149,
                        "voyage__voyage_ship__ship_name": "Sampson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 90645,
                        "voyage__voyage_ship__ship_name": "Enterprize",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1756",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 763,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 751
                    }, {
                        "voyage__voyage_id": 91198,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1765",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 539,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91199,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1767",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 544,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91200,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1769",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 81987,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1781",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81988,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1783",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81989,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1785",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81990,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1786",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 551,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 345
                    }, {
                        "voyage__voyage_id": 81991,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1788",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 740
                    }, {
                        "voyage__voyage_id": 81992,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81993,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81994,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 81995,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81996,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 90708,
                        "voyage__voyage_ship__ship_name": "Charming Peggy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1760",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 528,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 90709,
                        "voyage__voyage_ship__ship_name": "Charming Peggy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1760",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 528,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 396
                    }, {
                        "voyage__voyage_id": 91225,
                        "voyage__voyage_ship__ship_name": "Liberty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 570,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 91243,
                        "voyage__voyage_ship__ship_name": "Dispatch",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 551,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91756,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1772",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91757,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1772",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91758,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1774",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91258,
                        "voyage__voyage_ship__ship_name": "John",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 764
                    }, {
                        "voyage__voyage_id": 91775,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1772",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91776,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1773",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91777,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1774",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 80516,
                        "voyage__voyage_ship__ship_name": "Betsey",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80517,
                        "voyage__voyage_ship__ship_name": "Betsey",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80518,
                        "voyage__voyage_ship__ship_name": "Betsey",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80519,
                        "voyage__voyage_ship__ship_name": "Betsey",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1795",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91277,
                        "voyage__voyage_ship__ship_name": "William",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 80527,
                        "voyage__voyage_ship__ship_name": "Betsey",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90769,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1759",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 90770,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1761",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }, {
                        "voyage__voyage_id": 90771,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1762",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }, {
                        "voyage__voyage_id": 83612,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1788",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 516,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 83613,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 516,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83614,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 90786,
                        "voyage__voyage_ship__ship_name": "Spy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1759",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 27311,
                        "voyage__voyage_ship__ship_name": "Ferrett",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1763",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91322,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1767",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91323,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 82626,
                        "voyage__voyage_ship__ship_name": "Mary Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 82627,
                        "voyage__voyage_ship__ship_name": "Mary Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 516,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 82628,
                        "voyage__voyage_ship__ship_name": "Mary Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 82629,
                        "voyage__voyage_ship__ship_name": "Mary Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 551,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 90828,
                        "voyage__voyage_ship__ship_name": "Marquis of Granby",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1760",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }, {
                        "voyage__voyage_id": 90829,
                        "voyage__voyage_ship__ship_name": "Marquis of Granby",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1762",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 543,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 396
                    }, {
                        "voyage__voyage_id": 90840,
                        "voyage__voyage_ship__ship_name": "Wolfe",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1762",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }, {
                        "voyage__voyage_id": 91361,
                        "voyage__voyage_ship__ship_name": "Liberty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1767",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 91362,
                        "voyage__voyage_ship__ship_name": "Liberty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 91363,
                        "voyage__voyage_ship__ship_name": "Liberty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1769",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 90853,
                        "voyage__voyage_ship__ship_name": "Lively",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1762",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 90854,
                        "voyage__voyage_ship__ship_name": "Lively",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1764",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 82155,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1786",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 742
                    }, {
                        "voyage__voyage_id": 82156,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1787",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 82157,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 82158,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 82159,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 82160,
                        "voyage__voyage_ship__ship_name": "King Pepple",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91380,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1767",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91381,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 740
                    }, {
                        "voyage__voyage_id": 91383,
                        "voyage__voyage_ship__ship_name": "Dispatch",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91384,
                        "voyage__voyage_ship__ship_name": "Dispatch",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1769",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 91385,
                        "voyage__voyage_ship__ship_name": "Dispatch",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1771",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 81669,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1782",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 516,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 736
                    }, {
                        "voyage__voyage_id": 81670,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1783",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81671,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1785",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81672,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1787",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81673,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81674,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 81675,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91399,
                        "voyage__voyage_ship__ship_name": "Jenny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 376
                    }, {
                        "voyage__voyage_id": 91403,
                        "voyage__voyage_ship__ship_name": "Tom",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1767",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 751
                    }, {
                        "voyage__voyage_id": 90901,
                        "voyage__voyage_ship__ship_name": "Minerva",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1761",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 543,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }, {
                        "voyage__voyage_id": 81181,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1788",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81182,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81183,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81184,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 81185,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 81186,
                        "voyage__voyage_ship__ship_name": "Eliza",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 83757,
                        "voyage__voyage_ship__ship_name": "Thomas",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 83758,
                        "voyage__voyage_ship__ship_name": "Thomas",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83759,
                        "voyage__voyage_ship__ship_name": "Thomas",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 576,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90421,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1753",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 809,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 90423,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1753",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91448,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1768",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 741
                    }, {
                        "voyage__voyage_id": 91449,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1770",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91450,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1770",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 551,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 83272,
                        "voyage__voyage_ship__ship_name": "Ranger",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1790",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 83273,
                        "voyage__voyage_ship__ship_name": "Ranger",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 83274,
                        "voyage__voyage_ship__ship_name": "Ranger",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 740
                    }, {
                        "voyage__voyage_id": 83275,
                        "voyage__voyage_ship__ship_name": "Ranger",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 576,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91654,
                        "voyage__voyage_ship__ship_name": "Elizabeth",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1770",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 91655,
                        "voyage__voyage_ship__ship_name": "Elizabeth",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1771",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91656,
                        "voyage__voyage_ship__ship_name": "Elizabeth",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1772",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 551,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91657,
                        "voyage__voyage_ship__ship_name": "Elizabeth",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1773",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91658,
                        "voyage__voyage_ship__ship_name": "Elizabeth",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1774",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 92007,
                        "voyage__voyage_ship__ship_name": "Robert",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1775",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 543,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 727
                    }, {
                        "voyage__voyage_id": 92011,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1774",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 92012,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1775",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 92013,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1776",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 92014,
                        "voyage__voyage_ship__ship_name": "Jane",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1777",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91005,
                        "voyage__voyage_ship__ship_name": "Dolphin",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1763",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80254,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1787",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 80255,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80256,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1789",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 80257,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 558,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 80258,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 80259,
                        "voyage__voyage_ship__ship_name": "Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 91006,
                        "voyage__voyage_ship__ship_name": "Dolphin",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1764",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91525,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1769",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 91025,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1763",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90002,
                        "voyage__voyage_ship__ship_name": "Byrne",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1745",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 543,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90003,
                        "voyage__voyage_ship__ship_name": "Byrne",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1746",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 90004,
                        "voyage__voyage_ship__ship_name": "Byrne",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1748",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 376
                    }, {
                        "voyage__voyage_id": 90005,
                        "voyage__voyage_ship__ship_name": "Byrne",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1751",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 92563,
                        "voyage__voyage_ship__ship_name": "Tom",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1775",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 91035,
                        "voyage__voyage_ship__ship_name": "Richmond",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1764",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 764
                    }, {
                        "voyage__voyage_id": 91036,
                        "voyage__voyage_ship__ship_name": "Richmond",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 764
                    }, {
                        "voyage__voyage_id": 90534,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1755",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 727
                    }, {
                        "voyage__voyage_id": 90535,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1756",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 528,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91049,
                        "voyage__voyage_ship__ship_name": "Betty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1765",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 534,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90539,
                        "voyage__voyage_ship__ship_name": "Little Billy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1755",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 773
                    }, {
                        "voyage__voyage_id": 80813,
                        "voyage__voyage_ship__ship_name": "Charlotte",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1792",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 90548,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1755",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90549,
                        "voyage__voyage_ship__ship_name": "Knight",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1757",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 610,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 80340,
                        "voyage__voyage_ship__ship_name": "Archer",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1791",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 353
                    }, {
                        "voyage__voyage_id": 80341,
                        "voyage__voyage_ship__ship_name": "Archer",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1793",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 740
                    }, {
                        "voyage__voyage_id": 80342,
                        "voyage__voyage_ship__ship_name": "Archer",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91604,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1770",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91605,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1771",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91606,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1772",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91607,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1773",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91608,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1775",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 738
                    }, {
                        "voyage__voyage_id": 91609,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1776",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91101,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1764",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91102,
                        "voyage__voyage_ship__ship_name": "Nancy",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1765",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 522,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 91610,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1777",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }, {
                        "voyage__voyage_id": 91611,
                        "voyage__voyage_ship__ship_name": "Liberty",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1770",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 91612,
                        "voyage__voyage_ship__ship_name": "Fanny",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1771",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 528,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }]
                },
                "1008761": {
                    "id": 1008761,
                    "name": "Boats, Wm",
                    "voyages": []
                },
                "1008762": {
                    "id": 1008762,
                    "name": "Boates, William",
                    "voyages": []
                },
                "1010289": {
                    "id": 1010289,
                    "name": "Boates, William",
                    "voyages": [{
                        "voyage__voyage_id": 81676,
                        "voyage__voyage_ship__ship_name": "Gregson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": null,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": null
                    }, {
                        "voyage__voyage_id": 82630,
                        "voyage__voyage_ship__ship_name": "Mary Ann",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1794",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 566,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 359
                    }, {
                        "voyage__voyage_id": 90935,
                        "voyage__voyage_ship__ship_name": "Sampson",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1762",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 379
                    }]
                },
                "1013132": {
                    "id": 1013132,
                    "name": "Boats, Wm",
                    "voyages": [{
                        "voyage__voyage_id": 92526,
                        "voyage__voyage_ship__ship_name": "Ellis",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1776",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 542,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 360
                    }]
                },
                "1030417": {
                    "id": 1030417,
                    "name": "Boats, William",
                    "voyages": [{
                        "voyage__voyage_id": 91026,
                        "voyage__voyage_ship__ship_name": "Squirrel",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1766",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 532,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 728
                    }, {
                        "voyage__voyage_id": 90646,
                        "voyage__voyage_ship__ship_name": "Enterprize",
                        "voyage__voyage_dates__imp_arrival_at_port_of_dis": ",,1755",
                        "voyage__voyage_itinerary__imp_principal_place_of_slave_purchase_id": 748,
                        "voyage__voyage_itinerary__imp_principal_port_slave_dis_id": 278
                    }]
                },
                "1030418": {
                    "id": 1030418,
                    "name": "Boats, William",
                    "voyages": []
                },
                "1030419": {
                    "id": 1030419,
                    "name": "Boats, William",
                    "voyages": []
                },
                "1030420": {
                    "id": 1030420,
                    "name": "Boats, William",
                    "voyages": []
                }
            }
        }
    }
};

const makeLocalizedString = (s: string) =>
    new LocalizedString(
        s,
        new Map<LanguageCode, string>(LanguageCodes.map(lang => [lang, `${lang} [${s}]`]))
    );

export class MockEnslaversService implements IEnslaversService {
    _geoService = new MockGeoService();

    async createContribution(enslaverId: number | null, type: EnslaverContributionType): Promise<EnslaverContribution> {
        if (type === EnslaverContributionType.Edit) {
            const contrib = await parseEnslaverContribution(mockEditEnslaverContribData, this._geoService);
            if (contrib !== null) {
                return contrib;
            }
        }
        throw new Error("Method not implemented.");
    }

    saveContribution(contribution: EnslaverContribution): Promise<boolean> {
        throw new Error("Method not implemented.");
    }

}

export class MockGeoService implements IGeoService {
    getLocation = (id: number) =>
        Promise.resolve(new MapLocation(
            id,
            makeLocalizedString(`Place name ${id}`),
            null,
            null));
}

export class MockLocalizationService implements ILocalizationService {
    get = (key: string) => makeLocalizedString(key);
    fetchGroup = (group: string) => Promise.resolve(3);
}

export const MockServiceContext = new ServiceContext(
    new MockLocalizationService(),
    new MockGeoService(),
    new MockEnslaversService()
);